package Sigmaz.Lexer;

public enum TokenTipo {
    DESCONHECIDO, ID, NUMERO, COMENTARIO, TEXTO, CHAVE_ABRE, CHAVE_FECHA, PARENTESES_ABRE, PARENTESES_FECHA, VIRGULA, PONTOVIRGULA, ARROBA, SETA, DOISPONTOS, QUAD, IGUAL, COMPARADOR_IGUALDADE,COMPARADOR_DIFERENTE;
}
