package Sigmaz.Lexer;

public enum TokenTipo {
    DESCONHECIDO, ID, NUMERO, COMENTARIO, TEXTO, CHAVE_ABRE, CHAVE_FECHA, PARENTESES_ABRE, PARENTESES_FECHA, VIRGULA, PONTOVIRGULA, ARROBA, SETA, PONTO, DOISPONTOS, QUAD, IGUAL,ENVIAR, RECEBER,MENOR,MAIOR, COMPARADOR_IGUALDADE, COMPARADOR_DIFERENTE,SOMADOR,DIMINUIDOR,MULTIPLICADOR,DIVISOR,NEGADOR;
}
