package Sigmaz.S02_Lexer;

public enum TokenTipo {
    DESCONHECIDO, ID, INTEIRO,NUMERO_FLOAT, COMENTARIO_LINHA,COMENTARIO_BLOCO, TEXTO, CHAVE_ABRE, CHAVE_FECHA, PARENTESES_ABRE, PARENTESES_FECHA,COLCHETE_ABRE,COLCHETE_FECHA, VIRGULA, PONTOVIRGULA, ARROBA, SETA, PONTO, DOISPONTOS, QUAD, IGUAL,ENVIAR, RECEBER,MENOR,MAIOR, COMPARADOR_IGUALDADE, COMPARADOR_DIFERENTE,SOMADOR,DIMINUIDOR,MULTIPLICADOR,DIVISOR,NEGADOR,ANEXADOR;
}
