package AppSigmaz;

public enum Fases {
    EXECUTAR,
    IDENTAR,
    IDENTAR_TUDO,
    IDENTAR_BIBLIOTECAS,
    MONTAR_BIBLIOTECAS,
    ESTRUTURADOR,
    TESTES,
    DEPENDENCIAS,
    INTELLISENSE,
    INTELLISENSE_BIBLIOTECA,
    COMENTARIOS,
    TODO,
    INTERNO
}
