package AppSigmaz;

public enum Fases {
    LEXER,
    COMPILAR_EXECUTAVEL,
    COMPILAR_BIBLIOTECA,
    EXECUTAR,
    IDENTAR,
    IDENTAR_TUDO,
    IDENTAR_BIBLIOTECAS,
    MONTAR_BIBLIOTECAS,
    ESTRUTURADOR,
    TESTES,
    DEPENDENCIAS,
    INTELLISENSE,
    INTELLISENSE_BIBLIOTECA,
    COMENTARIOS,
    TODO,
    INTERNO,
    MAKE_LEXER,
    MAKE_EXECUTAR
}
